packages:
  - "."

onlyBuildDependencies:
  - esbuild
  - sharp
  - "@parcel/watcher"
  - "@parcel/watcher-linux-x64-glibc"
  - "@parcel/watcher-linux-x64-musl"
  - playwright
  - "@playwright/test"
  - lefthook
  - lightningcss
