name: Create Release PR

on:
  push:
    branches:
      - develop

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for existing PR with title "release"
        id: check_pr
        run: |
          PR_COUNT=$(gh pr list --base main --head develop --search "release in:title" --json title --jq '. | length')
          echo "PR_COUNT=$PR_COUNT" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release PR
        if: env.PR_COUNT == '0'
        run: gh pr create -B "main" -t "release" -b "Automated release PR from develop to main."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
