name: Create Release PR

on:
  push:
    branches:
      - develop

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create release pr
        run: gh pr create -B "main" -t "release" -b ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
