name: Tweet New Posts

on:
  pull_request:closed:
    branches:
      - feature/twitter-api
      - feature/twitter-api-test
    paths:
      - '_posts/**'

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install tweepy
        run: pip install os
        run: pip install sys
        run: pip install datetime
        run: pip install python-dotenv

      - name: Tweet
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          for filename in $(git diff origin/feature/twitter-api-test origin/feature/twitter-api --name-only --diff-filter=A -- '*.md') ; do
            python tweet.py $filename
          done
