name: Tweet New Posts

on:
  pull_request:
    types:
      - closed
    branches:
      - feature/twitter-api
    paths:
      - '_posts/**'

jobs:
  tweet:
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install tweepy

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Tweet
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          diff_files=$(git diff --name-only --diff-filter=A ${{ github.event.pull_request.base.sha }}.. -- '*.md')
          echo $diff_files
          for filename in ${diff_files} ; do
            python tweet.py $filename
          done
